name: "P2000 RTL-SDR"
version: "1.0.9"
slug: "p2000_rtlsdr"
description: "Receive P2000 events using Home Assistant and your RTL-SDR dongle"
startup: application
boot: auto
map:
  - config:rw
  - share:rw
  - ssl
url: https://github.com/cyberjunky/addon-p2000_rtlsdr
# uart: true
udev: true
usb: true
host_network: false
hassio_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mqtt:need
options:
  general:
    verbosity: normal
  mqtt:
    ha_autodiscovery: true
    ha_autodiscovery_topic: homeassistant
    base_topic: p2000_rtlsdr
    tls_enabled: false
    retain: false
  rtlsdr:
    cmd: "rtl_fm -f 169.65M -M fm -s 22050 | multimon-ng -a FLEX -t raw -"
  opencage:
    enabled: false
    token: ab1234567890cd
  p2000_global_filters:
    ignore_text: "*Test*,*test*,*TEST*"
    ignore_capcode: "123456789,987654321"
  p2000_sensors:
    - id: 2001
      name: P2000 Inside a Zone
      icon: mdi:ambulance
      zone_radius: 5
      zone_latitude: 52.37602835336776
      zone_longitude: 4.902929475786443
    - id: 2002
      name: P2000 GRIP
      icon: mdi:magnify
      keyword: "*GRIP*,*Grip*,*grip*"
    - id: 2003
      name: P2000 Lifeliners
      icon: mdi:counter
      capcode: "*001420059*,*000923993*,*000923995*,*000320591*"
    - id: 2004
      name: P2000 Region Amsterdam
      icon: mdi:map
      region: "Amsterdam-Amstelland"
    - id: 2005
      name: P2000 Brandweer
      icon: mdi:fire-truck
      discipline: "Brandweer"
  tts_replacements:
    - pattern: P1
      replacement: Prio 1
    - pattern: P2
      replacement: Prio 2
    - pattern: BOB\-[0-9][0-9]\s
      replacement: ""

schema:
  general:
    verbosity: list(debug|normal)
  mqtt:
    host: str?
    port: int?
    user: str?
    password: str?
    ha_autodiscovery: bool
    ha_autodiscovery_topic: str
    base_topic: str
    tls_enabled: bool
    tls_ca: str?
    tls_cert: str?
    tls_keyfile: str?
    tls_insecure: bool?
    retain: bool?
  rtlsdr:
    cmd: str
  opencage:
    enabled: bool
    token: str
  p2000_global_filters:
    ignore_text: str?
    ignore_capcode: str?
  p2000_sensors:
    - id: int
      name: str
      icon: str?
      region: str?
      keyword: str?
      capcode: str?
      discipline: str?
      zone_radius: float?
      zone_latitude: float?
      zone_longitude: float?
  tts_replacements:
    - pattern: str
      replacement: str
